name: wpf-ui-pr-validator

run-name: Running smoke test on ${{ inputs.chosen-runner }}
on:
  workflow_dispatch:
    inputs:
      chosen-runner:
        required: true
        type: choice
        options:
        - alex-arm64-linux
        - alex-arm64-windows
        - 4-core-ubuntu-benchmark-perf-test
        - 8-core-windows-benchmark-perf-test

jobs:
  build:
    runs-on: ${{ inputs.chosen-runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1.3
        with:
          msbuild-architecture: arm64
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - name: Setup .NET Core SDK 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build src\Wpf.Ui.Gallery\Wpf.Ui.Gallery.csproj --configuration Release --no-restore
